In [3]:
import pandas as pd

hcia_FI = pd.read_csv("HCNA.csv")
moodle_FI_email = pd.read_csv("Moodle.csv")

hcia_F_list = hcia_FI["Фамилия"].tolist()
hcia_I_list = hcia_FI["Имя"].tolist()
hcia_E_list = []

moodle_F_list = moodle_FI_email["Фамилия"].tolist()
moodle_I_list = moodle_FI_email["Имя"].tolist()
moodle_E_list = moodle_FI_email["Адрес электронной почты"].tolist()

hcia_moodleF_df = pd.DataFrame()
hcia_moodle_df = pd.DataFrame()
hcia_moodle = []

for i in range(60):
    for j in range(60):
        last_names = moodle_FI_email[moodle_FI_email["Фамилия"].isin([hcia_F_list[i]])]
        for k in range(60):
            first_last_names = last_names[last_names["Имя"].isin([hcia_I_list[j]])]
    
    hcia_moodle_df = pd.concat([hcia_moodleF_df, 
                                first_last_names], 
                                ignore_index=True)
hcia_moodle_df
#for i in range(60):
#    hcia_moodle_df = pd.concat([hcia_moodle_df,
#                               hcia_moodleF_df[hcia_moodleF_df["Имя"].isin([hcia_I_list[i]])]],
#                              ignore_index=True)

#    hcia_moodleI_df = pd.concat([hcia_moodleI_df, 
#                                moodle_FI_email[moodle_FI_email["Имя"].isin([hcia_I_list[i]])]], 
#                                ignore_index=True)



#moodle_FI_email[moodle_FI_email["Фамилия"].isin(["Зверев"])]

#moodle_FI_email[moodle_FI_email["Имя"].isin(["Кирилл"])]

#moodle_FI_email["Фамилия"].isin(["Зверев"])

,Фамилия,Имя,Адрес электронной почты,Состояние,Тест начат,Завершено,Затраченное время,"Оценка/100,00","В. 1 /3,33","В. 2 /3,33",...,"В. 21 /3,33","В. 22 /3,33","В. 23 /3,33","В. 24 /3,33","В. 25 /3,33","В. 26 /3,33","В. 27 /3,33","В. 28 /3,33","В. 29 /3,33","В. 30 /3,33"
0,Александров,Алексей,aaaleksandrov2002@mail.ru,Завершенные,12 Март 2020 17:52,12 Март 2020 18:26,33 мин. 42 сек.,"12,22","3,33",0,...,-,-,-,-,-,-,-,-,-,"1,11"